### ISSUE TITLE
Possible editing of multiple records during a single edit session

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#1782]
**Describe the bug**
@allysonlister reported a bug in our internal system that couldn't be reproduced by our technical team - yet (they are still working on it). However, @lnanderson, one of our community curators, has now reported similar behaviour and we're hoping that this extra information might help @knirirr et al. figure out what's happening.

Sometimes, when one record is being editing in the UI, one or more of the changes are saved on different records.

Apologies, this one looks tricky. Lindsey and I, in trying to figure out what we are both doing, are wondering if it has something to do with toggling tabs while performing multiple edits. We both often toggle back and forth among all the tabs, editing bits and pieces and saving intermittently. Could it be that when we toggle, sometimes we accidentally move to another record when you move tabs, just for that tab? One "next to it" in some way (alphabetically? via relationships? ids?) ?

**To Reproduce**

As I said, it is not easily reproducible, and @knirirr and the team are trying to reproduce it. So instead of steps to reproduce, we'll provide some examples here.

## Example 1: from Lindsey

@allysonlister queried an edit Lindsey performed:
> It actually seems as though the Kbase organisations were accidentally added to WholeCellKB's record (https://fairsharing.org/1701)? Please would you check, and update as required?

Lindsey replied:

> for record https://fairsharing.org/1701 (WholeCellKB). This is a bug I noticed a while back but since it keeps occurring and now is popping up elsewhere (based on your query of it), I figured we can elaborate on it here. This bug has popped up more than once for me, specifically for module entries in the “Licenses and Support Links” record field. During active/live curation, when I have saved input entries during live edits of my own, after  toggling back and forth across the other fields in the record edit, all of a sudden it either deletes and replaces my entries with other records that sharing similar naming schemas (like WholeCellKB and KBase, both have similar acronyms in the name). Like I mentioned this only occurs in this specific record field tab, and sometimes will auto backfill information from other records that I have not edited or have been associated with curating and replaces the resources I have added where I have had to go back and redo them. I have noticed if i back arrow in the browser and then refresh, it repopulates the information. It may be worth having a developer look at. If my explanation isn’t clear please let me know, it is a sort of complicated error to explain.

## Example 2: From @allysonlister 

> I have just been editing https://fairsharing.org/888 (Sickle Cell Disease Ontology (SCDO)) please see the record history if you wish, but I modified most every section of the record. One of the things I added was adding https://fairsharing.org/organisations/1207 as an organisation.
> I then approved this update in the dashboard. Then, just below 888 in the dashboard, I noticed https://fairsharing.org/1275 (Infectious Disease Ontology Core (IDO)) had an update pending for me. However, I promise I did NOT update that record (it is, however, related to 888 via its relationships).
> But for some reason, 1275's record history has me adding https://fairsharing.org/organisations/1207 to this record rather than 888. Further, although all of the other edits for 888 seem to be saved, it does NOT have https://fairsharing.org/organisations/1207.

**Comment by allysonlister** [comment]
Another example of the bug just happened.

![image](https://user-images.githubusercontent.com/143586/182385059-251d04d4-bc59-48b3-b9e0-c28abf8f47db.png)


The steps I was taking when this happened - I noticed something odd straight away. I plan to immediately fix Crossref after I write this comment, but you will still see the record history if you need to see what happened.

1. I was editing https://fairsharing.org/2289 - all sorts of tabs and fields, but the last couple of edits were a) adding Crossref (3037) as a relationship ('related to') to 2289 and then b) adding an organisation where previously there hadn't been one.
2. Adding the relationship seemed to work just fine. I think clicked the Organisation tab.
3. There was no organisations yet. I created a new organisation ("Coral Trait Database Administrators and Boards") and chose the "maintains" relationship.
4. I hit "save" for that organisation popup, and then it was back to displaying the organisation tab. 
5. However, **now, the organisation tab had two organisations when it should have had one**: The "coral trait administrators and boards", and ALSO "CrossRef, Lynnfield, MA, USA".
6. This was odd, so I deleted the cross ref organisation from 2289 and saved the record.
7. I then immediately opened record 3037 (Crossref) and as you can see from the image above, the same addition/deletion had also happened to 3037 silently!

again, this is odd, but perhaps these particular steps will help you reproduce the problem. I'll keep an eye on this ticket while I'm on leave. Thanks!

**Comment by allysonlister** [comment]
Finally, this morning I was editing many of the PDB-related records, but NOT record 1560 (CAPS-DB). It is likely that CAPS-DB does have (or did have) a relationship with one of those PDB-related records, however.

I've just noticed an edit "I" made to this record deleted a relationship (to a "null" record?). I definitely wasn't editing record 1560 this morning. I'll re-curate both of them now, but the issue remains...

![image](https://user-images.githubusercontent.com/143586/182389913-792b4f41-eb99-47e6-b653-fe22b7bed898.png)

**Comment by allysonlister** [comment]
Here's another. I saw this in the curation dashboard:
![Screenshot from 2022-08-02 14-53-41](https://user-images.githubusercontent.com/143586/182399632-8d362477-3f81-473e-9861-45cc75543df2.png)
Notice that there are two records that have "unknown" as the user who updated them?

I went into them, and 3536 seems to have lost a relationship to a "null" record?
![image](https://user-images.githubusercontent.com/143586/182399762-1a24b6fd-4643-4ebb-b489-588dc8dbc077.png)

and record 1982 seems to have lost a relationship to another "null" record?
![image](https://user-images.githubusercontent.com/143586/182399951-54370c5a-dc4b-4061-8493-b9a07d84abec.png)


This is most odd - again, I will now have to re-curate both of these records.

**Comment by knirirr** [comment]
> Finally, this morning I was editing many of the PDB-related records, but NOT record 1560 (CAPS-DB). It is likely that CAPS-DB does have (or did have) a relationship with one of those PDB-related records, however.
> 
> I've just noticed an edit "I" made to this record deleted a relationship (to a "null" record?). I definitely wasn't editing record 1560 this morning. I'll re-curate both of them now, but the issue remains...

This is, as far as I can tell, separate from some of the other goings-on described in this ticket. I've addressed it here: https://github.com/FAIRsharing/FAIRsharing-API/issues/581

**Comment by lnanderson** [comment]
@knirirr @allysonlister (in reference to above): The replacement issue is still persistent for me, and has occurred with 2 other records in the last week. I am not able to capture backend screenshots similar to Allyson's, however I did notice a similar pattern that occurs each time this issue occurs. There seems to be a consistent pattern associated with text recognition specifically and the amount of time a record is open for editing. It appears as if the backend deduplication features (maybe with either text mining devOps features where field content metadata recognition and integration tools have a bug?). At times I can't even get the stored organizations to pop up when I type in an existing record in addition to the replacement error I have been experiencing. The system seems to get acronyms confused and when it can't recognize the difference between similar records sharing identical or similar acronyms in the record name, the existing record feature quits. I only experience replacement issues under the "Licenses & Support Links" section, and existing organization record recognition (auto-replace selection errors) when adding/editing under the "Organizations & Grants" section. Not sure if they are interrelated issues or separate. If my feedback is unclear, please let me know. It is sort of hard to explain how the error occurs with this bug.

**Comment by knirirr** [comment]
> Another example of the bug just happened.
>   ....
> 
> again, this is odd, but perhaps these particular steps will help you reproduce the problem. I'll keep an eye on this ticket while I'm on leave. Thanks!

Unfortunately not; I followed those steps and, at step 5 where you saw an unwanted organisation, I encountered only the expected behaviour. 
At present I don't have any ideas and will have to keep looking.

**Comment by knirirr** [comment]
> There seems to be a consistent pattern associated with text recognition specifically and the amount of time a record is open for editing.

Are you able to give me any more information on what that pattern is, or how long a particular section must be left open before you observe these phenomena?

> (maybe with either text mining devOps features where field content metadata recognition and integration tools have a bug?). 

There's nothing of that sort running.


> The system seems to get acronyms confused and when it can't recognize the difference between similar records sharing identical or similar acronyms in the record name, the existing record feature quits. 

Can you give me any more details on this, please? I'm not sure what you mean by the existing record feature. Do you know of any means to demonstrate this problem?

> I only experience replacement issues under the "Licenses & Support Links" section, and existing organization record recognition (auto-replace selection errors) when adding/editing under the "Organizations & Grants" section. Not sure if they are interrelated issues or separate. If my feedback is unclear, please let me know. It is sort of hard to explain how the error occurs with this bug.

This one is not entirely clear to me either, I'm afraid. If you are able to lay out an example which consistently demonstrates the problem for you then I will try following it to see if I can find what the cause is.

**Comment by allysonlister** [comment]
One of our community curators updated https://fairsharing.org/307 and as part of that, added three organisations. Two of them are listed in the record history but are NOT in 307; rather, they have been added to 1339 with nothing put into 1339's record history.

![image](https://user-images.githubusercontent.com/143586/191272536-14e26f37-b021-4d37-9441-cfd0c70b0e04.png)
You can see above in this record history for 307 that two organisations should have been added; they are NOT in record 307, but are present in 1339.

The third, "BIDS Community", our curator had intended to add to 307 but the record history says he added it to 1339 and it is visible in 1339. Therefore it is hard to tell if the curator accidentally edited 1339 when they thought they were editing 307.

However such an accident is highly unlikely as the curator only intended on editing 307, and did as part of his edit add a relationship to 1339.

I will not approve or otherwise modify either 307 or 1339 until you've investigated. Because our curator did this rather than me, I can't give you any further information.

**Comment by knirirr** [comment]
Once again, I'm afraid I'm unable to replicate this problem. My attempts to edit record 307 in a test system resulted in the organisations being added to the correct record, as confirmed by interactions between client and server. So, I think I'll still need to see an editing session in action to stand a chance of identifying this issue. 

I've created a PR which adds the record ID to the edit form next to the record name, in case that's useful when continuing to look into this (see https://github.com/FAIRsharing/fairsharing.github.io/pull/1832).

**Comment by allysonlister** [comment]
I don't think the user sees any difference when they're editing - all signs point to this happening after someone updates and then saves a record. Perhaps try to replicate it by performing the same update, but at the same time also adding a relation to the other record, as our curator did. Try saving that relation either before or after the organisations are added, things like that. It's clear there is a bug here, it's just getting some useful data.

can you tell anything considering the record history shows the addition of organisations and they're not actually in the record? This seems to be a concrete place to start, to see if you can see what in the code caused the record history to be updated but the record to not have been modified.

**Comment by knirirr** [comment]
Restoring a backup from before these edits, then performing the same edits in the order given in the current logs still doesn't reproduce the problem, unfortunately. 
Modifications are applied separately for each tab and will be logged separately. 

> can you tell anything considering the record history shows the addition of organisations and they're not actually in the record? 

This would only suggest to me that they were added, then the record was modified to remove them _whilst skipping callbacks_. There's no indication of how this might happen and I can't reproduce it.

I have asked @ramGranell to attempt to reproduce also, as a second opinion would be very useful.

**Comment by ramGranell** [comment]
I have been trying to locally replicate the changes as the person commented and all seems to work properly. The organisations goes to the record 307 (I created some organisations to connect to record 307 before and after creating the relationship between the records).

**Comment by knirirr** [comment]
This has been fixed now the cause - clicking the "preview record" button on the record association editor tab - has been observed. This button was overwriting the store with the data it loaded (it is rather a complex form...).
